# .air.toml

root = "."
tmp_dir = "tmp"
include_ext = ["go"]
exclude_dir = ["client", "node_modules", "vendor", "tmp", ".git"]

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["client", "node_modules", "vendor", "tmp", ".git"]
  delay = 1000
  send_interrupt = true

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
